### ISSUE TITLE
ADDomain: DomainAdministratorCredential not using if new forest created

### ISSUE THREAD

**Issue by melchugin** [PowerShell/ActiveDirectoryDsc#156]
Hi.
I want to create new domain using xADDomain DSC resource. And can not understand, why after creating, domain administrator password is incorrect. It's not the same, like I specify it in DomainAdministratorCredential parameters.
I looked in the module's source code and find, that if created new forest (without parent domain), this parameter does not use.
So, could you make DomainAdministratorCredential optional parameter?
After all, when I create a new domain with new forest, I must specify this fake parameter.

Thank you in advance.

**Comment by iainbrighton** [comment]
@melchugin The DomainAdministratorCredential parameter is used to query whether the domain exists or not. The domain's Administrator password __will be the password that was the machine's local Administrator account password before promotion to a domain controller__. Does this answer your questions?

**Comment by melchugin** [comment]
Oh, yes. I miss this.
Thank you alot.
I think you could close this issue.

**Comment by johlju** [comment]
Label this as documentation and help wanted, so that someone in the community can run with this.

**Comment by Absoblogginlutely** [comment]
From my understanding and reading of Readme.MD (line 99) I think this issue is actually closed?.

**Comment by johlju** [comment]
Closing this issue as per previous comment. It is noted in the Wiki that it is used for searching for existence of the domain.
