### ISSUE TITLE
ADOptionalFeature: New Resource (to replace ADRecycleBin)

### ISSUE THREAD

**Issue by rdbartram** [PowerShell/ActiveDirectoryDsc#162]
I'm about to create a pull request for a new resource to support any ADOptionalFeature.

I needed to be able to activate the "Privileged Access Management Feature" on a domain controller and realised this feature didn't already exist.

The question is should this resource supersede xADRecycleBin?

Perhaps its easier for people not in the know to simply turn on the recycle bin this way, but is it not better to have a generic resource and pass "Recycle Bin Feature" as the key parameter?

Discuss :)

**Comment by johlju** [comment]
@rdbartram I personally feel like having such a resource would be unnatural PowerShell-wise. It wouldn't be obvious to use the resource to turn on different features.  It would be more natural if there was a setup program where you could choose different options. But if this is different, for example, cmdlets, I would propose that these new "feature" get's it own resource. But I can be convinced to use an "generic optional feature resource" for this if the community likes that idea more.

Another question. Could this, "recycle bin feature" and "Privileged Access Management Feature" be a parameter on any existing resource instead, like xADDomain?

**Comment by johlju** [comment]
@rdbartram I take back my previous comments. Since there is a cmdlet to set these options `Enable-ADOptionalFeature` I see that a resource xADOptionalFeature could work here. It would be natural to use in a configuration.

**Comment by johlju** [comment]
@rdbartram do you have a resource for this to send in, or maybe in a repo that you can share so I can help to get it in here?

**Comment by rdbartram** [comment]
sure let me find it.

**Comment by rdbartram** [comment]
I create a WIP PR. I need to complete the unit tests and then you can review it.

**Comment by johlju** [comment]
Awesome! Thank you! 😃
