### ISSUE TITLE
ADGroup: When ManagedBy is set to SamAccountName the Test-TargetResource fail

### ISSUE THREAD

**Issue by johlju** [PowerShell/ActiveDirectoryDsc#164]
In the README.md for the parameter `ManagedBy` it says

>ManagedBy: Specifies the user or group that manages the group object (optional).
>Valid values are the user's or group's DistinguishedName, ObjectGUID, SID or SamAccountName.

It is true for the function `Set-TargetResource`, but in reality only DistinguishedName can be used by the function `Test-TargetResource`, because DN is what the code evaluates.

https://github.com/PowerShell/xActiveDirectory/blob/e858c98fceb3e1b2039ea9a0884e66cac0bdc8cb/DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1#L244-L248

The actual value of property `ManagedBy`.

```
[DBG]: PS > $adGroup


Description            : Designated administrators of the domain
DisplayName            : 
DistinguishedName      : CN=Domain Admins,CN=Users,DC=company,DC=local
GroupCategory          : Security
GroupScope             : Global
ManagedBy              : CN=MyAdmin,CN=Users,DC=company,DC=local
Name                   : Domain Admins
ObjectClass            : group
ObjectGUID             : 748b817d-e1fe-4112-9a24-aa5265ca006c
SamAccountName         : Domain Admins
SID                    : S-1-5-21-4235145154-3114286989-3040194990-512
WriteDebugStream       : {}
WriteErrorStream       : {}
WriteInformationStream : {}
WriteVerboseStream     : {}
WriteWarningStream     : {}
```

The configuration:
```
       xADGroup AddSecondAdministratorToDomainAdmin
        {
            GroupName        = 'Domain Admins'
            MembersToInclude = 'MyExtraAdmin'
            ManagedBy        = 'MyAdmin'

            Credential       = $EnterpriseAdministratorCredential
        }
```

**Comment by iainbrighton** [comment]
@johlju Correct - that text was copied from the Set-ADUser cmdlet. I'd change the readme it to say only the DN is supported.

**Comment by johlju** [comment]
Thats the easiest solution. But would it not be possible to query for the user object using the value in `$adGroup.ManagedBy`. With that user object Maybe we could compare if any of the four properties match the parameter `ManagedBy`.

**Comment by johlju** [comment]
Although I see my suggested solution could potentially be a problem if the user set as `Credential` does not have permission to read the user that is set in `ManagedBy`. Can that occur?

**Comment by johlju** [comment]
My last suggestion will add more logic to the resource, and since nobody else thought being able to be able to use anything else than DN i will close this. 🙂
