### ISSUE TITLE
ADComputer: How to add user to the adcomputer object

### ISSUE THREAD

**Issue by mohamednazar** [PowerShell/ActiveDirectoryDsc#171]
Hi,

I am able to create computer object in AD using xADComputer module. Now I am looking how to assign user to that computer object? Please find the screenshot for more info. 

![image](https://user-images.githubusercontent.com/23080585/33814541-dd4d7ac4-de50-11e7-9c11-a7b7ee349305.png)

Please help!

Regards,
Mohamed Nazar

**Comment by johlju** [comment]
@mohamednazar There are currently no resource for doing this. If you can, then please help us create it.
I'm in need of it too.

**Comment by johlju** [comment]
Assume the new resource in ADObjectPermissionEntry resolved this, if it did not, then please reopen.
