### ISSUE TITLE
ADDomain: Raising Domain and Forest Functional Level: Resource or extension to ADDomain needed

### ISSUE THREAD

**Issue by nyanhp** [PowerShell/ActiveDirectoryDsc#200]
It should be possible to raise the domain and forest functional level with DSC as well. I propose a new resource so as not to pollute xADDomain, but I would like to hear what the community thinks.

If this is implemented in xADDomain the behavior of Set-TargetResource needs to be overhauled a bit to support raising only the DFL/FFL for an existing domain/forest. In this case a Force parameter would be useful here to indicate that raising the DFL/FFL is something that is not easily reversible.

**Comment by johlju** [comment]
I like the idea of the `Force` parameter. Although I think a separate resource for this might be better as this is something you should thoughtfully do, and adding a separate resource would clear show in the configuration that a raising of function levels are done. But I'm good with either option.
