### ISSUE TITLE
ADComputer: Disabled computer account after the initial set

### ISSUE THREAD

**Issue by brwilkinson** [PowerShell/ActiveDirectoryDsc#248]
When creating AD resources, including the Computer account often they are used for Cluster Name Objects (CNO).

Often we pre-stage computer accounts for the CNO in a particular OU in ActiveDirectory, so that when the cluster comes only it has permissions to reset the cluster account password and enable the account.

The ability to create a computer account that is not enabled was added to this resource a while ago, however ideally you wouldn't want a Test-DSCResource to fail because the account was enabled later on.

Currently that is the way the resource has been implemented. .

I would like to propose that we remove the Enabled check from the Test.

**Comment by johlju** [comment]
This is being worked on in PR #170. I haven't had the time to take it up again yet (a lot of maintainer work keeps me busy 🙂 ). Feel free to continue the work on that PR.

**Comment by johlju** [comment]
I don't think we can remove the Enabled check. Please look at the PR #170 and see if it solves this issue.

**Comment by brwilkinson** [comment]
@johlju right I saw that one. . . I felt like that matched with how the current default is right. so I wasn't sure if it was abandoned. 

I will test that code and follow up over there.

**Comment by johlju** [comment]
This is resolved in the latest release.
