### ISSUE TITLE
WaitForADDomain: Handle timeout better

### ISSUE THREAD

**Issue by johlju** [PowerShell/ActiveDirectoryDsc#343]
The current code uses a for-loop to wait for the domain to be accessible. 

https://github.com/PowerShell/xActiveDirectory/blob/44ca75e062beff431cf41e1efb89d71bc4a5d044/DSCResources/MSFT_xWaitForADDomain/MSFT_xWaitForADDomain.psm1#L90-L109

I suggest that we instead use `Start-Job -ScriptBlock {]` and `Wait-Job -Timeout`. The code in the `- ScriptBlock` will continuously try to access the domain before the timeout. If the job haven't returned before the timeout, then the it can be assumed the domain is not yet available and the rest of the logic is run as appropriate.

**Comment by tmeckel** [comment]
Neat idea because that would allow the specification of a "real" timeout as a parameter and not those two arguments which only in combination will show the time the function will wait for the Domain to become available. More intuitive to use. But a breaking change if the "old" two parameters will be removed.

**Comment by johlju** [comment]
Yes, but I think it's better to change the parameters, right? Proposing this schema

```
[ClassVersion("1.0.0.0"), FriendlyName("xWaitForADDomain")]
class MSFT_xWaitForADDomain : OMI_BaseResource
{
    [Key, Description("Specifies the fully qualified domain name to wait for.")] String DomainName;
    [Write, Description("Specifies the credentials that are used when accessing the domain, unless the built-in PsDscRunAsCredential is used."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Specifies the timeout in seconds that the resource will wait for the domain to be accessible.")] uint64 WaitTimeout;
    [Write, Description("Specifies the number of times the node will be reboot in an effort to connect to the domain.")] uint32 RebootCount;
};
```

**Comment by tmeckel** [comment]
I totally agree, but it's a "major" breaking change, so perhaps a more gradual phase out of the old parameters would be nice. Like we started with the firewall stuff in xDSCWebService https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/536#issuecomment-468975278

**Comment by johlju** [comment]
It’s possible to do that, or we gather a lot of breaking changes and do them at once. Next release would be a breaking change release already so would be good to get more breaking changes in. But not sure if someone have time to resolve this issue until then.
