### ISSUE TITLE
ADReplicationSiteLink: Integration tests is missing for this resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/ActiveDirectoryDsc#356]
We should add integration tests for this resource.

**Comment by 1800Zeta** [comment]
Hi @johlju 

To do the integration tests for the Site Links, existing sites will need to be created beforehand. Should I put the New-ADReplicationSite commands in the Try of the integration.tests.ps1 file just after the configFile = join-path or should I put them elsewhere? I will add a remove-ADReplicationSite at the end of the tests.

**Comment by johlju** [comment]
I usually make a prerequisites integration test that creates dependencies using DSC. That integration test only runs the Start test and I skip Get-test and Test-test. 

If that is not possible, there are no DSC resources to make why you need, then add the necessary code in the Before

**Comment by johlju** [comment]
See example here https://github.com/PowerShell/ActiveDirectoryDsc/blob/ae42a2cb0eecb4b5f4f2abcb74edd5de58bb20a6/Tests/Integration/MSFT_ADObjectEnabledState.config.ps1#L32

**Comment by 1800Zeta** [comment]
Perfect thank you very much. Will do that 👍
