### ISSUE TITLE
ADUser: Add additional properties

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/ActiveDirectoryDsc#44]
I would love to be able to set additional properties on xADUser resource, like department and phone numbers etc..

This would be great for our lab and demo setups! Any requests, before I get to work?

**Comment by mattmcnabb** [comment]
Iain,

I totally agree! I've done some extensive AD user automation in the last couple years and I have a new project coming up in this space. I have considered considered building what I have done out into a reusable framework for user automation. However, with DSC now in full swing I believe the AD resource could be this framework.

I've been thinking about how to go about this and would love to contribute as well. In my mind I'd like to be able to pull data in from SQL, CSV, etc. and build a table of users and attributes that can then be acted on. Maybe this table would go into ConfigurationData?

Ultimately I'd like to be able to set and attribute of a user, their group membership, modify attributes when necessary, and enable or disable when necessary. Does this sound too ambitious?

**Comment by iainbrighton** [comment]
The pulling data from SQL and CSV would be done by a composite resource or via ConfigurationData (that's what I'm using for our training and lab environments). This resource is pretty much done, I'm just testing internally.

Here's the current syntax I have working and will push shortly:
```
xADUser [string] #ResourceName
{
    DomainName = [string]
    Password = [PSCredential]
    UserName = [string]
    [ City = [string] ]
    [ Company = [string] ]
    [ Country = [string] ]
    [ Department = [string] ]
    [ DependsOn = [string[]] ]
    [ Description = [string] ]
    [ DisplayName = [string] ]
    [ Division = [string] ]
    [ DomainAdministratorCredential = [PSCredential] ]
    [ DomainController = [string] ]
    [ EmailAddress = [string] ]
    [ EmployeeID = [string] ]
    [ EmployeeNumber = [string] ]
    [ Enabled = [bool] ]
    [ Ensure = [string] { Absent | Present }  ]
    [ Fax = [string] ]
    [ GivenName = [string] ]
    [ HomeDirectory = [string] ]
    [ HomeDrive = [string] ]
    [ HomePage = [string] ]
    [ HomePhone = [string] ]
    [ Initials = [string] ]
    [ JobTitle = [string] ]
    [ LogonScript = [string] ]
    [ Manager = [string] ]
    [ MobilePhone = [string] ]
    [ Notes = [string] ]
    [ Office = [string] ]
    [ OfficePhone = [string] ]
    [ PasswordNeverExpires = [bool] ]
    [ Path = [string] ]
    [ POBox = [string] ]
    [ PostalCode = [string] ]
    [ ProfilePath = [string] ]
    [ SamAccountName = [string] ]
    [ State = [string] ]
    [ StreetAddress = [string] ]
    [ Surname = [string] ]
    [ UserPrincipalName = [string] ]
}
```
As you can see it's a bit of a monster :)

**Comment by mattmcnabb** [comment]
It is huge, but at the same time there is plenty more it could do, like Exchange attributes. That's what makes this a real challenge. Looks like your well on your way here, though! Hopefully we can mold this into something really flexible and usable.

Nice work, can't wait to see the PR!

**Comment by iainbrighton** [comment]
@mattmcnabb - that sounds like you volunteering?! The PR has been submitted but has a merge conflict in the readme that requires someone to merge some existing PRs. You can always use this: https://github.com/iainbrighton/xActiveDirectory/commits/dev that has all those PRs in it..

**Comment by iainbrighton** [comment]
Implemented in PR #49.

However, I need to implement setting a person's picture stored in AD. It can be added into the xADUser resource, but this is probably an edge-case. Therefore, should it be added to xADUser or put into a separate xADUserPicture resource? @TravisEz13 @HemantMahawar ?

**Comment by TravisEz13** [comment]
If it's an optional property, I don't see a problem with keeping it in xADUser and  when it is not assigned it doesn't affect the stability of the resource.  Then again, I agree its probably not going to be used enough that a separate resource wouldn't be horrible and might even be prefered if when not assigned it will affect the stability of the resource.  @HemantMahawar @BrucePay What do you think?

**Comment by iainbrighton** [comment]
@TravisEz13 @HemantMahawar @BrucePay Any decision on this? I have [implemented it here](https://github.com/VirtualEngine/VirtualEngineLab/tree/master/DSCResources/VE_vADUserThumbnailPhoto) as I needed it for our lab environment. The thumbnail can either be specified as a file path to a .jpg or a Base64-encoded jpg.

I'm happy to add the contribution either to the xADUser resource or as a separate resource, but need to know what direction you want to take..

**Comment by kilasuit** [comment]
I agree that this thumbnail property should be added to xADUser

Re properties that are added as part of an AD Schema extension I think these properties should be in a new resource named along the lines of xADUserExtendedSchema as these aren't always going to be required so can be used or not used as needed

**Comment by iainbrighton** [comment]
@TravisEz13 @HemantMahawar @BrucePay Are you in agreement with @kilasuit that this should be added to xADUser?

**Comment by johlju** [comment]
@iainbrighton Are you still able to work on this? 

Can we just add this to the xADUser resource with requirement that it requires for example the 2008 Schema? If a future property needs xxxx schema, then that is a requirement to use the property, it doesn't stop the resource from functioning. It will just ignore fetch those properties that are not supported. Would that work?

**Comment by albvar** [comment]
Can we add ChangePasswordAtLogon to this as well?

**Comment by johlju** [comment]
I'm looking at fixing this issue by adding the ThumbnailPhoto property to ADUser. Continuing the work @iainbrighton started and reuses parts of the MIT licensed code he implemented in https://github.com/VirtualEngine/VirtualEngineLab/tree/master/DSCResources/VE_vADUserThumbnailPhoto
