### ISSUE TITLE
PSScriptAnalyzer: Enable default rules 

### ISSUE THREAD

**Issue by SSvilen** [PowerShell/ActiveDirectoryDsc#491]
I have noticed that the default rules for PSScriptAnalyzer were not enabled, although a bunch of them are part of IncludeRules array. 
Adding following line in analyzersettings.psd1 would enable them:
IncludeDefaultRules = $true

**Comment by johlju** [comment]
I thought using `IncludeRules` added them.

>When you use the CustomizedRulePath parameter, you can use this parameter to include standard rules and rules in the custom rule paths.
>https://github.com/PowerShell/PSScriptAnalyzer/blob/master/docs/markdown/Invoke-ScriptAnalyzer.md

You mean that the above quote assumes the `IncludeDefaultRules = $true` have been added?

I see under `CustomRulePath` that it says

>Uses only the custom rules defined in the specified paths to the analysis. To still use the built-in rules, add the -IncludeDefaultRules switch.

**Comment by johlju** [comment]
I tested this and I agree. It does not hit the rules in the include list. Great catch @SSvilen! 😃

**Comment by SSvilen** [comment]
I have the PR waiting on submit button. :)

**Comment by johlju** [comment]
Happy to merge when you send it in :)
